name: Autodeploy to Jino

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.VPS_GITHUB_ACTIONS }}

      - name: Autodeploy to Jino
        run: |
          ssh -o StrictHostKeyChecking=no root@195.161.62.158 "
          cd /var/www/etiketkasales_frontend || git clone git@github.com:etiketkasales/etiketkasales_frontend.git /var/www/etiketkasales_frontend;
          cd /var/www/etiketkasales_frontend;
          git reset --hard;
          git pull origin main;
          npm install;
          npm run build;
          systemctl restart etiketkasales;
          "
